data:
  dataset: {name: dataset_final, samples: 96201, type: private}
  datasetLoadOption: batch
  kfold: 1
  mapping:
    CodigoCliente:
      options: {Normalization: false, Scaling: 1}
      port: Ignore
      shape: ''
      type: Numeric
    DebitoAutomatico:
      options: {}
      port: InputPort0
      shape: ''
      type: Categorical
    Edad:
      options: {Normalization: false, Scaling: 1}
      port: InputPort0
      shape: ''
      type: Numeric
    IdBehaviour:
      options: {}
      port: Ignore
      shape: ''
      type: Categorical
    IdSubtema:
      options: {}
      port: Ignore
      shape: ''
      type: Categorical
    IdTema:
      options: {}
      port: OutputPort0
      shape: ''
      type: Categorical
    Score:
      options: {Normalization: false, Scaling: 1}
      port: InputPort0
      shape: ''
      type: Numeric
    TasaEOL:
      options: {Normalization: false, Scaling: 1}
      port: InputPort0
      shape: ''
      type: Numeric
    TasaIUS:
      options: {Normalization: false, Scaling: 1}
      port: InputPort0
      shape: ''
      type: Numeric
    TipoPersona:
      options: {}
      port: InputPort0
      shape: ''
      type: Categorical
  numPorts: 1
  samples: {split: 1, test: 0, training: 76960, validation: 19240}
  shuffle: true
model:
  connections:
  - {source: Dense_1, target: Dropout_1}
  - {source: Dense_3, target: Output_2}
  - {source: Dropout_1, target: Dense_2}
  - {source: Dense_2, target: Dropout_2}
  - {source: Dropout_2, target: Dense_3}
  - {source: Input_1, target: Dense_1}
  layers:
  - args: {}
    class: Input
    name: Input_1
    x: 58
    y: 47
  - args: {activation: relu, output_dim: '100'}
    class: Dense
    name: Dense_1
    x: 45
    y: 226
  - args: {p: '0.3'}
    class: Dropout
    name: Dropout_1
    x: 55
    y: 339
  - args: {activation: relu, output_dim: '50'}
    class: Dense
    name: Dense_2
    x: 392
    y: 230
  - args: {p: '0.3'}
    class: Dropout
    name: Dropout_2
    x: 398
    y: 348
  - args: {activation: softmax, output_dim: '7'}
    class: Dense
    name: Dense_3
    x: 758
    y: 505
  - args: {}
    class: Output
    name: Output_2
    x: 758
    y: 623
params:
  advance_params: true
  batch_size: 32
  is_custom_loss: false
  loss_func: categorical_crossentropy
  num_epoch: 5
  optimizer: {name: Adadelta}
project: recomendador-errepar-tema
